workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/apk/release/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  ios-workflow:
    name: iOS App Store Build
    instance_type: mac_mini_m1
    max_build_duration: 120

    environment:
      groups:
        - iOS_AppStore_Keys
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gagcars.gordonautogarage
      vars:
        BUNDLE_ID: "com.gagcars.gordonautogarage"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APPLE_TEAM_ID: "5NPA9TJU9H"  # Added as variable instead

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Debug Apple connection
        script: |
          echo "=== DEBUG INFO ==="
          echo "Bundle ID: com.gagcars.gordonautogarage"
          echo "Team ID: $APPLE_TEAM_ID"
          echo "Distribution: app_store"
          
          # List profiles with team ID
          xcode-project list-profiles --team-id "$APPLE_TEAM_ID" || echo "Cannot list profiles"

      - name: Setup code signing
        script: |
          keychain initialize
          
          # Try to use profiles with explicit team ID
          xcode-project use-profiles \
            --bundle-id "com.gagcars.gordonautogarage" \
            --team-id "$APPLE_TEAM_ID" \
            --type ios_app_store || echo "Profile setup failed, continuing..."

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: FQCQY4FVSL
        issuer_id: a9e4a6f2-11cc-438c-accd-b7697d923db1
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true