workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/apk/release/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  ios-workflow:
    name: iOS App Store Build
    instance_type: mac_mini_m1
    max_build_duration: 120

    environment:
      groups:
        - iOS_AppStore_Keys
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gagcars.gordonautogarage
        team_id: "5NPA9TJU9H"  # ← ADDED: Explicit team ID

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..

      - name: Debug code signing setup
        script: |
          echo "=== CODE SIGNING DEBUG ==="
          echo "Bundle ID: com.gagcars.gordonautogarage"
          echo "Team ID: 5NPA9TJU9H"
          echo "Distribution: app_store"
          
          # Check available signing identities
          echo "=== AVAILABLE SIGNING IDENTITIES ==="
          security find-identity -v -p codesigning || echo "No code signing identities found"
          
          # Check provisioning profiles
          echo "=== AVAILABLE PROFILES ==="
          xcode-project list-profiles || echo "Cannot list profiles"

      - name: Force device build (not simulator)
        script: |
          echo "=== FORCING DEVICE BUILD ==="
          # Set environment to build for device, not simulator
          export SUPPORTS_MACCATALYST=NO
          export SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD=NO

      - name: Build iOS IPA
        script: |
          echo "=== BUILDING FOR iOS DEVICE ==="
          # Build for device with no-codesign first to test
          flutter build ipa \
            --release \
            --no-codesign \  # ← TEMPORARY: Bypasses simulator signing issue
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - edemkweku.jerrykanfra@gmail.com  # ← CHANGE TO YOUR EMAIL
        notify:
          success: true
          failure: true