workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - iOS_AppStore_Keys
      flutter: stable
    
    scripts:
      # ONLY 3 STEPS - minimal approach
      - name: Get packages
        script: |
          flutter clean
          flutter pub get
      
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
      
      - name: List output
        script: |
          ls -la build/ios/ipa/ 2>/dev/null || echo "Build directory not found"
    
    artifacts:
      - build/ios/ipa/*.ipa