workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  ios-workflow:
    name: iOS App Store Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - iOS_AppStore_Keys
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..
      - name: Setup ExportOptions.plist
        script: |
          echo "Creating ExportOptions.plist..."
          cd ios
          rm -f ExportOptions.plist
          echo '<?xml version="1.0" encoding="UTF-8"?>' > ExportOptions.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> ExportOptions.plist
          echo '<plist version="1.0">' >> ExportOptions.plist
          echo '<dict>' >> ExportOptions.plist
          echo '  <key>method</key>' >> ExportOptions.plist
          echo '  <string>app-store</string>' >> ExportOptions.plist
          echo '  <key>teamID</key>' >> ExportOptions.plist
          echo '  <string>5NPA9TJU9H</string>' >> ExportOptions.plist
          echo '</dict>' >> ExportOptions.plist
          echo '</plist>' >> ExportOptions.plist
          echo "ExportOptions.plist created successfully"
          cd ..
      - name: Import certificates manually
        script: |
          echo "=== IMPORTING CERTIFICATES MANUALLY ==="
          
          # List available identities BEFORE import
          echo "Available signing identities:"
          security find-identity -v -p codesigning || echo "No identities found"
          
          # Try to find and use the specific certificate
          CERT_NAME="iPhone Distribution: Sendyfile LLC (5NPA9TJU9H)"
          echo "Searching for: $CERT_NAME"
          
          # Check if certificate exists
          if security find-identity -v -p codesigning | grep -q "$CERT_NAME"; then
            echo "✓ Certificate found in keychain"
            CERT_HASH=$(security find-identity -v -p codesigning | grep "$CERT_NAME" | awk '{print $2}' | head -1)
            echo "Certificate hash: $CERT_HASH"
          else
            echo "✗ Certificate NOT found in keychain"
            echo "Trying to list all identities:"
            security find-identity -v -p codesigning
          fi
      - name: Build iOS IPA
        script: |
          echo "Building iOS IPA with Xcode..."
          cd ios
          
          # Clean
          xcodebuild clean -workspace Runner.xcworkspace -scheme Runner || true
          
          # Archive with manual signing override
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ../build/ios/Runner.xcarchive \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=5NPA9TJU9H \
            PROVISIONING_PROFILE_SPECIFIER="GAGCar_AppStore_Profile" \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGN_IDENTITY="iPhone Distribution"
          
          # Check if archive was created
          if [ -d "../build/ios/Runner.xcarchive" ]; then
            echo "✓ Archive created successfully"
            
            # Export IPA
            xcodebuild -exportArchive \
              -archivePath ../build/ios/Runner.xcarchive \
              -exportOptionsPlist ExportOptions.plist \
              -exportPath ../build/ios/ipa \
              -allowProvisioningUpdates
            
            echo "✓ IPA exported successfully"
          else
            echo "✗ Archive failed to create"
            echo "Checking build directory:"
            ls -la ../build/ios/
          fi
          
          cd ..
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - edemkweku.jerrykanfra@gmail.com
        notify:
          success: true
          failure: true