workflows:
  ios-manual-signing:
    name: iOS Manual Signing
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - iOS_AppStore_Keys
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        TEAM_ID: 5NPA9TJU9H
        BUNDLE_ID: com.gagcars.gordonautogarage
    
    scripts:
      # 1. Get Flutter packages FIRST
      - name: Get packages
        script: |
          flutter clean
          flutter pub get
      
      # 2. Install CocoaPods
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      
      # 3. Manual signing setup
      - name: Manual signing setup
        script: |
          echo "=== MANUAL SIGNING SETUP ==="
          
          # IMPORTANT: Create directories first
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          mkdir -p build/ios/ipa/
          
          echo "Team ID: $TEAM_ID"
          echo "Bundle ID: $BUNDLE_ID"
      
      # 4. Build with Flutter - FIXED YAML SYNTAX
      - name: Build with Flutter signing
        script: |
          echo "=== BUILDING WITH FLUTTER SIGNING ==="
          
          # Create ExportOptions.plist using echo (no EOF issues)
          cd ios
          echo '<?xml version="1.0" encoding="UTF-8"?>' > ExportOptions.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> ExportOptions.plist
          echo '<plist version="1.0">' >> ExportOptions.plist
          echo '<dict>' >> ExportOptions.plist
          echo '    <key>method</key>' >> ExportOptions.plist
          echo '    <string>app-store</string>' >> ExportOptions.plist
          echo '    <key>teamID</key>' >> ExportOptions.plist
          echo '    <string>5NPA9TJU9H</string>' >> ExportOptions.plist
          echo '</dict>' >> ExportOptions.plist
          echo '</plist>' >> ExportOptions.plist
          
          echo "ExportOptions.plist created:"
          cat ExportOptions.plist
          
          cd ..
          
          # Build with Flutter
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist \
            --verbose 2>&1 | tail -50
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - edemkweku.jerrykanfra@gmail.com