workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/apk/release/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  ios-workflow:
    name: iOS App Store Build
    instance_type: mac_mini_m1
    max_build_duration: 120

    environment:
      groups:
        - iOS_AppStore_Keys
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gagcars.gordonautogarage

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..

      - name: Debug code signing setup
        script: |
          echo "=== CODE SIGNING DEBUG ==="
          echo "Bundle ID: com.gagcars.gordonautogarage"
          echo "Distribution: app_store"
          
          # List available identities
          security find-identity -v -p codesigning || echo "No code signing identities found"
          
          # List provisioning profiles
          xcode-project list-profiles || echo "Cannot list profiles"

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - edemkweku.jerrykanfra@gmail.com  # ← CHANGE TO YOUR EMAIL
        notify:
          success: true
          failure: true