workflows:
  ios-workflow:
    name: iOS App Store Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - iOS_AppStore_Keys
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..
      - name: Create ExportOptions.plist
        script: |
          echo "Creating ExportOptions.plist..."
          cd ios
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > ExportOptions.plist
          echo "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">" >> ExportOptions.plist
          echo "<plist version=\"1.0\">" >> ExportOptions.plist
          echo "<dict>" >> ExportOptions.plist
          echo "    <key>method</key>" >> ExportOptions.plist
          echo "    <string>app-store</string>" >> ExportOptions.plist
          echo "    <key>teamID</key>" >> ExportOptions.plist
          echo "    <string>5NPA9TJU9H</string>" >> ExportOptions.plist
          echo "</dict>" >> ExportOptions.plist
          echo "</plist>" >> ExportOptions.plist
          cd ..
      - name: Build with Flutter (no codesign)
        script: |
          echo "=== BUILDING WITH --no-codesign ==="
          # Build IPA without signing first
          flutter build ipa --release --no-codesign --verbose
          
          echo "✓ App built without signing"
          echo "IPA will need manual signing before App Store upload"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - edemkweku.jerrykanfra@gmail.com
        notify:
          success: true
          failure: true
